"""Full-document loader owned by the R1 agent.

This loader returns the complete regulation document(s) so R1 can read every
page before producing its profile.

PDF sizes (current, live registry sources only):
  EnEfG.pdf              15 pages  ~14k tokens
  CELEX_32003L0087       15 pages  ~14k tokens
  CELEX_32022L2464       66 pages  ~71k tokens

All current documents fit below `DOC_TOKEN_BUDGET`. The token guard triggers a
chunked map-reduce fallback when a future document exceeds that threshold.

Markdown sources (e.g. `regulations/esrs/2026/ESRS_E1_2026.md`, generated by
`scripts/pull_esrs_docs.py`) are split into pages on top-level `## ` headings.
Any `![alt](path)` image reference in a page is resolved and returned alongside
that page's text so R1 can pass it through to a vision-capable LLM call.
"""
from __future__ import annotations

import base64
import hashlib
import re
from pathlib import Path
from typing import Any

from pypdf import PdfReader

from epoch_switch import config
from epoch_switch.core.envelope import CaseEnvelope


DOC_TOKEN_BUDGET: int = 90_000  # single-call threshold (~chars/4 estimate)

_IMAGE_MEDIA_TYPES = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".gif": "image/gif",
}
_MD_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")


class R1DocumentLoader:
    """Load all pages of regulation PDFs referenced by a CaseEnvelope."""

    # ── Public API ─────────────────────────────────────────────────────

    def hashes(self, envelope: CaseEnvelope) -> dict[str, str]:
        """Return sha256 hex for each regulation source (byte read only — fast).

        For Markdown sources, embedded image assets are hashed too (keyed by
        their path relative to REGULATIONS_DIR) so a replaced figure invalidates
        the R1 cache signature exactly like a replaced source document does.
        """
        result: dict[str, str] = {}
        for source_ref in envelope.regulation_refs:
            filename = self._require_filename(envelope, source_ref)
            path = self._source_path(filename)
            result[filename] = hashlib.sha256(path.read_bytes()).hexdigest()
            if path.suffix.lower() == ".md":
                for _alt, rel_path in _MD_IMAGE_RE.findall(path.read_text(encoding="utf-8")):
                    image_path = (path.parent / rel_path).resolve()
                    if image_path.is_file():
                        key = str(image_path.relative_to(config.REGULATIONS_DIR.resolve()))
                        result[key] = hashlib.sha256(image_path.read_bytes()).hexdigest()
        return result

    def load(
        self, envelope: CaseEnvelope
    ) -> tuple[list[dict[str, Any]], dict[str, str]]:
        """Return (all_pages, source_hashes).

        all_pages is a flat list of dicts:
            {source_ref, source_file, page, text}
        source_hashes maps filename -> sha256 hex.
        """
        all_pages: list[dict[str, Any]] = []
        source_hashes: dict[str, str] = {}

        for source_ref in envelope.regulation_refs:
            filename = self._require_filename(envelope, source_ref)
            path = self._source_path(filename)
            source_hashes[filename] = hashlib.sha256(path.read_bytes()).hexdigest()

            if path.suffix.lower() == ".md":
                all_pages.extend(self._load_markdown(source_ref, filename, path))
                continue

            reader = PdfReader(path)
            for page_number, pdf_page in enumerate(reader.pages, start=1):
                text = " ".join((pdf_page.extract_text() or "").split())
                if not text:
                    continue
                all_pages.append(
                    {
                        "source_ref": source_ref,
                        "source_file": filename,
                        "page": page_number,
                        "text": text,
                        "images": [],
                    }
                )

        return all_pages, source_hashes

    @staticmethod
    def estimate_tokens(pages: list[dict[str, Any]]) -> int:
        """Rough token estimate: total_chars / 4."""
        return sum(len(p.get("text", "")) for p in pages) // 4

    # ── Private helpers ─────────────────────────────────────────────────

    @staticmethod
    def _require_filename(envelope: CaseEnvelope, source_ref: str) -> str:
        filename = envelope.regulation_sources.get(source_ref)
        if not filename:
            raise ValueError(
                f"No regulation source configured for {source_ref}"
            )
        return filename

    @staticmethod
    def _source_path(filename: str) -> Path:
        """Resolve path and reject traversal attempts (nested subdirs allowed)."""
        regulations_dir = config.REGULATIONS_DIR.resolve()
        path = (regulations_dir / filename).resolve()
        if not path.is_relative_to(regulations_dir) or not path.is_file():
            raise ValueError(f"Invalid regulation source: {filename}")
        return path

    @classmethod
    def _load_markdown(
        cls, source_ref: str, filename: str, path: Path
    ) -> list[dict[str, Any]]:
        """Split a Markdown regulation source into pages on `## ` headings.

        Each page mirrors the PDF page dict shape (source_ref, source_file,
        page, text) plus `heading` (for readable citations) and `images`
        (embedded figures referenced via `![alt](relpath)` in that section).
        """
        raw = path.read_text(encoding="utf-8")
        sections = re.split(r"(?m)^## ", raw)
        pages: list[dict[str, Any]] = []
        # sections[0] is the document header (title + metadata) before the
        # first "## " heading; keep it as page 1 if it has content.
        preamble = sections[0].strip()
        body_sections = sections[1:]
        page_number = 1
        if preamble:
            pages.append(
                {
                    "source_ref": source_ref,
                    "source_file": filename,
                    "page": page_number,
                    "heading": None,
                    "text": " ".join(preamble.split()),
                    "images": cls._extract_images(preamble, path),
                }
            )
            page_number += 1
        for section in body_sections:
            heading, _, rest = section.partition("\n")
            text = " ".join(rest.split())
            if not text and not heading.strip():
                continue
            pages.append(
                {
                    "source_ref": source_ref,
                    "source_file": filename,
                    "page": page_number,
                    "heading": heading.strip(),
                    "text": text,
                    "images": cls._extract_images(rest, path),
                }
            )
            page_number += 1
        return pages

    @staticmethod
    def _extract_images(markdown_text: str, md_path: Path) -> list[dict[str, Any]]:
        images: list[dict[str, Any]] = []
        for alt, rel_path in _MD_IMAGE_RE.findall(markdown_text):
            image_path = (md_path.parent / rel_path).resolve()
            if not image_path.is_file():
                continue
            media_type = _IMAGE_MEDIA_TYPES.get(image_path.suffix.lower())
            if media_type is None:
                continue
            images.append(
                {
                    "path": str(image_path),
                    "media_type": media_type,
                    "data_b64": base64.b64encode(image_path.read_bytes()).decode("ascii"),
                    "alt": alt,
                }
            )
        return images
