"""D3 — deterministic per-site computation engines.

Three engines live here, selected by ``computation_spec.kind``:

``SiteComplianceEngine`` (kind="threshold"):
    Receives D1's already-scoped energy data product and a list of RecipeEntry
    values derived from the registry ThresholdSpec, and emits a D3Result with
    per-site × per-rule obligation status.

    Classification bands (0.95 default):
        obligated   : avg_3yr >= threshold
        near_breach : near_breach_ratio * threshold <= avg_3yr < threshold
        compliant   : avg_3yr < near_breach_ratio * threshold

    Gap is defined as avg_3yr - threshold (negative = below threshold).

``DualMethodReconciliationEngine`` (kind="dual_method"):
    Receives D1's already-scoped emissions data product and a ComputationSpec.
    For each site × fiscal year it reads two pre-summed columns from the
    emissions table (Method A: energy-derived scope2_market_proxy_t; Method B:
    reported scope2_location_t) and computes the absolute delta, percentage
    difference, and a material-discrepancy flag (|delta| > tolerance * max(A, B)).

``DivisionConsolidationEngine`` (kind="consolidation"):
    Receives D1's already-scoped emissions data product (entity_grain=bu_rc)
    and a ComputationSpec.  Groups rows by division (``group_by_column``, default
    ``bu_rc_group``) and optionally by ``time_period``, sums the declared
    ``measure_column`` (default ``scope2_location_t``), and rolls the division
    sub-totals into a single portfolio total.  Produced for UC3 (CSRD ESRS E1
    Scope 2 group disclosure).

Design mirrors DataQualityEngine in d2_missing_value:
- Pure pandas — no LLM, no I/O, no EvidenceStore.
- Fully testable in isolation.
- Recipe / spec is always supplied by the caller from case-level registry
  constants, never generated by an LLM at runtime ("case ister, analist istemez").
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

import pandas as pd
from pydantic import BaseModel


# ── Shared helper ──────────────────────────────────────────────────────────────

def _read_table(data_product: dict[str, Any], source_domain: str) -> list[dict]:
    """Return the row-dict list for *source_domain* from a D1 data product.

    Returns an empty list when the domain is absent, so callers can treat
    empty output as a natural skip rather than an error.
    """
    return (
        data_product.get("tables", {})
        .get(source_domain, {})
        .get("data", [])
    )


# ── Threshold engine — result models ──────────────────────────────────────────

class SiteObligationRow(BaseModel):
    """Compliance result for one site × one threshold rule."""

    location_id: str
    location_name: str
    rule_id: str
    rule_label: str
    threshold: float
    avg_3yr: float
    gap: float
    status: Literal["obligated", "near_breach", "compliant"]
    near_breach: bool
    years_used: list[str]
    # Geo passthrough — sourced from D1 rows; empty string when absent in data.
    country: str = ""
    country_code: str = ""
    country_name: str = ""
    cdp_region: str = ""
    # Full address from D1 locations join (dist_ie_locations.csv keyed by location_id).
    city: str = ""
    address: str = ""
    zip_code: str = ""
    latitude: str = ""
    longitude: str = ""


class D3Result(BaseModel):
    """Full computation result produced by SiteComplianceEngine."""

    kind: Literal["threshold"] = "threshold"
    registry_id: str
    column: str
    rows: list[SiteObligationRow]
    site_count: int
    n_obligated: int
    n_near_breach: int
    n_compliant: int


# ── Threshold engine — recipe ──────────────────────────────────────────────────

@dataclass
class RecipeEntry:
    """One threshold rule to evaluate per site.

    Built deterministically from registry ThresholdSpec by the calling agent
    (_build_recipe in TimeSeriesComputeAgent).  Never set by an LLM.
    """

    threshold_id: str
    rule_label: str
    column: str
    threshold_value: float
    near_breach_ratio: float = 0.95


# ── Threshold engine ───────────────────────────────────────────────────────────

class SiteComplianceEngine:
    """Deterministic per-site compliance computation engine (kind="threshold").

    Groups D1's energy table by site, averages the target column across the
    available fiscal years, and classifies each site × rule pair against the
    threshold bands.  Table key is controlled by *source_domain* (default
    ``"energy"``).
    """

    def compute(
        self,
        data_product: dict[str, Any],
        recipe: list[RecipeEntry],
        *,
        registry_id: str = "",
        source_domain: str = "energy",
    ) -> D3Result:
        """Compute per-site compliance rows from D1's energy table.

        Args:
            data_product: D1 output dict with shape
                ``{"tables": {source_domain: {"data": [row_dicts]}}}``.
            recipe: one RecipeEntry per threshold rule to evaluate.
            registry_id: forwarded verbatim into D3Result for traceability.
            source_domain: D1 table key to read (default ``"energy"``).

        Returns:
            D3Result.  ``rows`` is empty when no data is present or the
            recipe is empty.
        """
        energy_rows = _read_table(data_product, source_domain)
        column_first = recipe[0].column if recipe else ""

        if not energy_rows or not recipe:
            return D3Result(
                registry_id=registry_id,
                column=column_first,
                rows=[],
                site_count=0,
                n_obligated=0,
                n_near_breach=0,
                n_compliant=0,
            )

        df = pd.DataFrame(energy_rows)
        year_col = "time_period" if "time_period" in df.columns else None

        # Geo columns present in the data (sourced from D1 dimension joins).
        # Constant per location_id; carried as first non-null value per site.
        _GEO_COLS = (
            "country", "country_code", "country_name", "cdp_region",
            "city", "address", "zip_code", "latitude", "longitude",
        )

        rows: list[SiteObligationRow] = []

        for entry in recipe:
            col = entry.column
            if col not in df.columns:
                continue

            # Identify grouping columns present in data
            group_cols = [c for c in ("location_id", "location_name") if c in df.columns]
            if not group_cols:
                continue

            # Per-site 3-year average: mean of annual site×year sums.
            # D1 already aggregates to site×year grain; D3 averages across years.
            site_means = (
                df.groupby(group_cols, as_index=False, sort=False)[col]
                .mean()
            )

            for _, site_row in site_means.iterrows():
                avg = float(site_row[col]) if pd.notna(site_row[col]) else 0.0
                threshold = entry.threshold_value
                near_ratio = entry.near_breach_ratio
                gap = avg - threshold

                if avg >= threshold:
                    status: Literal["obligated", "near_breach", "compliant"] = "obligated"
                    is_near = False
                elif avg >= near_ratio * threshold:
                    status = "near_breach"
                    is_near = True
                else:
                    status = "compliant"
                    is_near = False

                loc_id = str(site_row.get("location_id", ""))
                loc_name = str(site_row.get("location_name", loc_id))

                # Collect fiscal years seen for this site (audit transparency)
                if year_col and "location_id" in df.columns:
                    mask = df["location_id"] == site_row.get("location_id")
                    years_used = sorted(
                        str(y) for y in df.loc[mask, year_col].dropna().unique()
                    )
                elif year_col:
                    years_used = sorted(
                        str(y) for y in df[year_col].dropna().unique()
                    )
                else:
                    years_used = []

                # Geo passthrough: first non-null value for this location_id.
                # Geo columns are dimension attributes — constant per site.
                if "location_id" in df.columns:
                    site_df = df.loc[df["location_id"] == site_row.get("location_id")]
                else:
                    site_df = df
                geo: dict[str, str] = {}
                for gcol in _GEO_COLS:
                    if gcol in df.columns:
                        vals = site_df[gcol].dropna()
                        geo[gcol] = str(vals.iloc[0]) if len(vals) > 0 else ""
                    else:
                        geo[gcol] = ""

                rows.append(
                    SiteObligationRow(
                        location_id=loc_id,
                        location_name=loc_name,
                        rule_id=entry.threshold_id,
                        rule_label=entry.rule_label,
                        threshold=threshold,
                        avg_3yr=round(avg, 4),
                        gap=round(gap, 4),
                        status=status,
                        near_breach=is_near,
                        years_used=years_used,
                        country=geo["country"],
                        country_code=geo["country_code"],
                        country_name=geo["country_name"],
                        cdp_region=geo["cdp_region"],
                        city=geo["city"],
                        address=geo["address"],
                        zip_code=geo["zip_code"],
                        latitude=geo["latitude"],
                        longitude=geo["longitude"],
                    )
                )

        site_count = len({r.location_id for r in rows})
        n_obligated = sum(1 for r in rows if r.status == "obligated")
        n_near_breach = sum(1 for r in rows if r.status == "near_breach")
        n_compliant = sum(1 for r in rows if r.status == "compliant")

        return D3Result(
            registry_id=registry_id,
            column=column_first,
            rows=rows,
            site_count=site_count,
            n_obligated=n_obligated,
            n_near_breach=n_near_breach,
            n_compliant=n_compliant,
        )


# ── Dual-method engine — result models ────────────────────────────────────────

class SiteReconciliationRow(BaseModel):
    """CO₂e reconciliation result for one site × one fiscal year."""

    location_id: str
    location_name: str
    year: str
    method_a: float          # energy-derived CO₂e (scope2_market_proxy_t)
    method_b: float          # reported Scope 2 CO₂e (scope2_location_t)
    method_a_label: str
    method_b_label: str
    abs_delta: float         # |method_a - method_b|
    pct_diff: float          # abs_delta / max(method_a, method_b)
    discrepancy_flag: bool   # pct_diff > tolerance
    # Geo passthrough — sourced from D1 rows; empty string when absent in data.
    country: str = ""
    country_code: str = ""
    country_name: str = ""
    cdp_region: str = ""
    # Full address from D1 locations join (dist_ie_locations.csv keyed by location_id).
    city: str = ""
    address: str = ""
    zip_code: str = ""
    latitude: str = ""
    longitude: str = ""


class ReconciliationResult(BaseModel):
    """Full computation result produced by DualMethodReconciliationEngine."""

    kind: Literal["dual_method"] = "dual_method"
    registry_id: str
    source_domain: str
    method_a_column: str
    method_b_column: str
    tolerance: float
    rows: list[SiteReconciliationRow]
    site_count: int
    n_flagged: int           # rows where discrepancy_flag is True


# ── Dual-method engine ────────────────────────────────────────────────────────

class DualMethodReconciliationEngine:
    """Deterministic per-site dual-method CO₂e reconciliation (kind="dual_method").

    Reads ``tables[source_domain]`` from the D1 data product.  D1 already
    pre-sums the raw rows per site × fiscal_year × scope and zeroes non-Scope-2
    values in the two method columns, so a simple sum within each
    (location_id, location_name, time_period) group collapses any residual
    scope-label rows and yields the annual site total for each method.

    Arithmetic:
        abs_delta = |method_a - method_b|
        denom     = max(method_a, method_b)
        pct_diff  = abs_delta / denom  (0.0 when denom == 0)
        flag      = pct_diff > tolerance
    """

    def compute(
        self,
        data_product: dict[str, Any],
        spec: Any,  # ComputationSpec — typed as Any to avoid circular import
        *,
        registry_id: str = "",
    ) -> ReconciliationResult:
        """Compute per-site dual-method reconciliation rows.

        Args:
            data_product: D1 output dict with the emissions table present.
            spec: ``ComputationSpec`` instance (kind="dual_method").
            registry_id: forwarded into ReconciliationResult for traceability.

        Returns:
            ReconciliationResult.  ``rows`` is empty when the emissions table
            is missing or when neither method column is present.
        """
        source_domain: str = getattr(spec, "source_domain", "emissions")
        col_a: str = getattr(spec, "method_a_column", "scope2_market_proxy_t")
        col_b: str = getattr(spec, "method_b_column", "scope2_location_t")
        label_a: str = getattr(spec, "method_a_label", col_a)
        label_b: str = getattr(spec, "method_b_label", col_b)
        tolerance: float = float(getattr(spec, "tolerance", 0.05))

        raw_rows = _read_table(data_product, source_domain)

        empty = ReconciliationResult(
            registry_id=registry_id,
            source_domain=source_domain,
            method_a_column=col_a,
            method_b_column=col_b,
            tolerance=tolerance,
            rows=[],
            site_count=0,
            n_flagged=0,
        )

        if not raw_rows:
            return empty

        df = pd.DataFrame(raw_rows)

        # Both method columns must be present; skip gracefully if absent.
        if col_a not in df.columns or col_b not in df.columns:
            return empty

        time_col = "time_period" if "time_period" in df.columns else None
        group_cols = [c for c in ("location_id", "location_name") if c in df.columns]
        if not group_cols:
            return empty
        if time_col:
            group_cols = group_cols + [time_col]

        # Sum within each site×year group.  D1 already zeroed non-Scope-2 rows
        # in these columns, so the sum is the annual Scope-2 site total.
        grouped = (
            df.groupby(group_cols, as_index=False, sort=False)[[col_a, col_b]]
            .sum()
        )

        # Geo columns present in the data (constant per location_id).
        _GEO_COLS = (
            "country", "country_code", "country_name", "cdp_region",
            "city", "address", "zip_code", "latitude", "longitude",
        )

        rows: list[SiteReconciliationRow] = []
        for _, r in grouped.iterrows():
            a = float(r[col_a]) if pd.notna(r[col_a]) else 0.0
            b = float(r[col_b]) if pd.notna(r[col_b]) else 0.0
            abs_delta = abs(a - b)
            denom = max(a, b)
            pct_diff = abs_delta / denom if denom else 0.0
            flag = pct_diff > tolerance

            # Geo passthrough: first non-null value for this location_id.
            loc_id_val = r.get("location_id")
            if "location_id" in df.columns and loc_id_val is not None:
                site_df = df.loc[df["location_id"] == loc_id_val]
            else:
                site_df = df
            geo: dict[str, str] = {}
            for gcol in _GEO_COLS:
                if gcol in df.columns:
                    vals = site_df[gcol].dropna()
                    geo[gcol] = str(vals.iloc[0]) if len(vals) > 0 else ""
                else:
                    geo[gcol] = ""

            rows.append(
                SiteReconciliationRow(
                    location_id=str(r.get("location_id", "")),
                    location_name=str(r.get("location_name", r.get("location_id", ""))),
                    year=str(r[time_col]) if time_col else "",
                    method_a=round(a, 4),
                    method_b=round(b, 4),
                    method_a_label=label_a,
                    method_b_label=label_b,
                    abs_delta=round(abs_delta, 4),
                    pct_diff=round(pct_diff, 6),
                    discrepancy_flag=flag,
                    country=geo["country"],
                    country_code=geo["country_code"],
                    country_name=geo["country_name"],
                    cdp_region=geo["cdp_region"],
                    city=geo["city"],
                    address=geo["address"],
                    zip_code=geo["zip_code"],
                    latitude=geo["latitude"],
                    longitude=geo["longitude"],
                )
            )

        site_count = len({r.location_id for r in rows})
        n_flagged = sum(1 for r in rows if r.discrepancy_flag)

        return ReconciliationResult(
            registry_id=registry_id,
            source_domain=source_domain,
            method_a_column=col_a,
            method_b_column=col_b,
            tolerance=tolerance,
            rows=rows,
            site_count=site_count,
            n_flagged=n_flagged,
        )


# ── Consolidation engine — result models ──────────────────────────────────────

class DivisionSubtotalRow(BaseModel):
    """Scope 2 CO₂e sub-total for one division × one fiscal year."""

    division: str        # bu_rc_group value (e.g. "DI", "SMO")
    year: str            # time_period value (e.g. "FY2024"), or "" when absent
    subtotal_t: float    # sum of measure_column for this division × year
    n_sites: int         # distinct location_id values contributing
    n_rows: int          # raw row count after grouping


class ConsolidationResult(BaseModel):
    """Full computation result produced by DivisionConsolidationEngine."""

    kind: Literal["consolidation"] = "consolidation"
    registry_id: str
    source_domain: str
    measure_column: str
    group_by_column: str
    rows: list[DivisionSubtotalRow]
    portfolio_total_t: float   # sum of all division sub-totals
    division_count: int        # distinct divisions in result
    site_count: int            # distinct location_id values across all rows


# ── Consolidation engine ───────────────────────────────────────────────────────

class DivisionConsolidationEngine:
    """Deterministic per-division Scope 2 CO₂e consolidation (kind="consolidation").

    Groups D1's emissions table by ``group_by_column`` (division) and optionally
    ``time_period``, sums ``measure_column`` within each group, and rolls the
    division sub-totals into a portfolio total.

    The approved handoff (isolated memory) determines which rows D1 delivers —
    entity_grain=bu_rc means D1 already delivers one row per division × year.
    This engine sums any residual row fan-out and assembles the ConsolidationResult.
    """

    def compute(
        self,
        data_product: dict[str, Any],
        spec: Any,  # ComputationSpec — typed as Any to avoid circular import
        *,
        registry_id: str = "",
    ) -> ConsolidationResult:
        """Compute per-division sub-totals and the portfolio total.

        Args:
            data_product: D1 output dict with the emissions table present.
            spec: ``ComputationSpec`` instance (kind="consolidation").
            registry_id: forwarded into ConsolidationResult for traceability.

        Returns:
            ConsolidationResult.  ``rows`` is empty when the table is absent
            or the grouping / measure column is missing.
        """
        source_domain: str = getattr(spec, "source_domain", "emissions")
        group_by: str = getattr(spec, "group_by_column", "bu_rc_group")
        measure: str = getattr(spec, "measure_column", "scope2_location_t")

        raw_rows = _read_table(data_product, source_domain)

        empty = ConsolidationResult(
            registry_id=registry_id,
            source_domain=source_domain,
            measure_column=measure,
            group_by_column=group_by,
            rows=[],
            portfolio_total_t=0.0,
            division_count=0,
            site_count=0,
        )

        if not raw_rows:
            return empty

        df = pd.DataFrame(raw_rows)

        if group_by not in df.columns or measure not in df.columns:
            return empty

        time_col = "time_period" if "time_period" in df.columns else None
        group_cols = [group_by]
        if time_col:
            group_cols = group_cols + [time_col]

        # Sum the measure within each division × year group.
        grouped = df.groupby(group_cols, as_index=False, sort=False).agg(
            subtotal_t=(measure, "sum"),
            n_rows=(measure, "count"),
        )

        # Count distinct sites per group for provenance.
        if "location_id" in df.columns:
            site_counts = (
                df.groupby(group_cols, as_index=False)["location_id"]
                .nunique()
                .rename(columns={"location_id": "n_sites"})
            )
            grouped = grouped.merge(site_counts, on=group_cols, how="left")
        else:
            grouped["n_sites"] = 0

        rows: list[DivisionSubtotalRow] = []
        for _, r in grouped.iterrows():
            rows.append(
                DivisionSubtotalRow(
                    division=str(r[group_by]),
                    year=str(r[time_col]) if time_col else "",
                    subtotal_t=round(float(r["subtotal_t"]) if pd.notna(r["subtotal_t"]) else 0.0, 4),
                    n_sites=int(r.get("n_sites", 0)),
                    n_rows=int(r.get("n_rows", 0)),
                )
            )

        portfolio_total_t = round(sum(r.subtotal_t for r in rows), 4)
        division_count = len({r.division for r in rows})
        site_count = (
            int(df["location_id"].nunique()) if "location_id" in df.columns else 0
        )

        return ConsolidationResult(
            registry_id=registry_id,
            source_domain=source_domain,
            measure_column=measure,
            group_by_column=group_by,
            rows=rows,
            portfolio_total_t=portfolio_total_t,
            division_count=division_count,
            site_count=site_count,
        )
